src/Entity/Worker.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WorkerRepository")
 */
class Worker
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $company_name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $position;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $telephone_1;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $telephone_2;

    /**
     * @ORM\Column(type="string", length=15, nullable=true)
     */
    private $telephone_3;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->company_name;
    }

    public function setCompanyName(?string $company_name): self
    {
        $this->company_name = $company_name;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(?string $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getTelephone1(): ?string
    {
        return $this->telephone_1;
    }

    public function setTelephone1(?string $telephone_1): self
    {
        $this->telephone_1 = $telephone_1;

        return $this;
    }

    public function getTelephone2(): ?string
    {
        return $this->telephone_2;
    }

    public function setTelephone2(?string $telephone_2): self
    {
        $this->telephone_2 = $telephone_2;

        return $this;
    }

    public function getTelephone3(): ?string
    {
        return $this->telephone_3;
    }

    public function setTelephone3(?string $telephone_3): self
    {
        $this->telephone_3 = $telephone_3;

        return $this;
    }
}

src/Controller/ManagementController.php
<?php

namespace App\Controller;

use App\Entity\Worker;
use phpDocumentor\Reflection\Types\Integer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ManagementController extends AbstractController
{
    /**
     * редирект с "/" на рабочую страницу
     * отправка на фронт нужного количества работников в зависимости от выбранной страницы пагинации
     * @Route("/", name="main")
     */
    public function main() {
        return $this->redirectToRoute("management", ['id' => 1]);
    }


    /**
     * отправка на фронт нужного количества работников в зависимости от выбранной страницы пагинации
     * @Route("/management/{id}", name="management", requirements={"id"="\d+"})
     * @param Integer $id
     * @return Response
     */
    public function index($id)
    {
        $size = 10;

        $countOfWorkers = count($this->getDoctrine()->getRepository(Worker::class)->findAll());

        $countOfPages = $countOfWorkers / 10;
        if ($countOfWorkers % 10 > 0)
        {
            $countOfPages++;
        }

        // массив с индексами для twig
        $indexes = [];
        for ($i = 1; $i <= $countOfPages; $i++)
        {
            array_push($indexes, $i);
        }


        // находим нужный интервал рабочих с заданным смещением
        $workers = $this
            ->getDoctrine()
            ->getRepository(Worker::class)
            ->findWorkersByInterval($id, $size);


        return $this->render('management/alluser.html.twig', [
            'controller_name' => 'ManagementController',
            'workers' => $workers,
            'current' => $id,
            'indexes' => $indexes,
            'countOfWorkers' => $countOfWorkers,
        ]);
    }

    /**
     * переход на страницу просмотра всех записей, редирект на первую страницу в пагинации
     * @Route("/management", name="management_redirect")
     */
    public function indexRedirect()
    {
        return $this->redirectToRoute("management", ['id' => 1]);
    }

    /**
     * рендер страницы добавления нового пользователя
     * @Route("/management/create", name="create_user")
     */
    public function addUserPage()
    {
        return $this->render('management/create.html.twig');
    }

    /**
     * Добавление нового юзера
     * @Route("/management/add", name="add_user", methods={"POST"})
     */
    public function addNewUser()
    {
        $entityManager = $this->getDoctrine()->getManager();

        $worker = $this->getWorkerFromPost();

        // обработка ошибок, проверка на дублирование email
        try {
            $entityManager->persist($worker);
            $entityManager->flush();
            return $this->render('management/create.html.twig', [
                'success_mess' => $_POST["first_name"].' успешно добавлен'
            ]);
        }
        catch (\Exception $ex) {
            $error_message = '';
            if ($ex->getErrorCode() == 1062)
            {
                $error_message = 'Такой емэйл уже есть!';
            } else
            {
                $error_message = 'Незапланированная ошибка';
            }
            return $this->render('management/create.html.twig', [
                'error_list' => $error_message,
                'first_name' => $worker->getFirstName(),
                'last_name' => $worker->getLastName(),
                'email' => $worker->getEmail(),
                'company_name' => $worker->getCompanyName(),
                'position' => $worker->getPosition(),
                'phone_1' => $worker->getTelephone1(),
                'phone_2' => $worker->getTelephone2(),
                'phone_3' => $worker->getTelephone3(),
            ]);
        }
    }

    /**
     * Удаление записи о рабочем
     * @Route ("/management/delete/{id}", name="delete_by_id", requirements={"id"="\d+"})
     * @param $id
     * @return RedirectResponse
     */
    public function deleteWorker($id) {
        $entityManager = $this->getDoctrine()->getManager();
        $repositoryWorkers = $this->getDoctrine()->getRepository(Worker::class);
        $worker = $repositoryWorkers->find($id);
        $entityManager->remove($worker);
        $entityManager->flush();
        return $this->redirectToRoute('management_redirect');
    }

    /**
     * получение полей Worker по посту
     * @return Worker
     */
    private function getWorkerFromPost() {
        $worker = new Worker();

        $worker->setFirstName($_POST["first_name"]);
        $worker->setLastName($_POST["last_name"]);
        $worker->setEmail($_POST["email"]);
        $worker->setCompanyName($_POST["company_name"]);
        $worker->setPosition($_POST["position"]);
        $worker->setTelephone1($_POST["telephone_1"]);
        $worker->setTelephone2($_POST["telephone_2"]);
        $worker->setTelephone3($_POST["telephone_3"]);

        return $worker;
    }
}

templates/management/alluser.html.twig
{% extends 'base.html.twig' %}

{% block title %}Все пользователи{% endblock %}

{% block body %}
    <div class="b-popup mx-auto fixed-top" style="width: 600px" id="editForm">
        <div class="card">
            <form class="px-4 py-3" method="post"  id="edit_user" action="">
                <div class="form-group">
                    <label>Имя *</label>
                    <input name="first_name" id="first_name_popup" type="text" class="form-control" required {% if first_name is defined %}
                        value="{{ first_name }}" {% endif %}>
                </div>
                <div class="form-group">
                    <label>Фамилия *</label>
                    <input name="last_name" id="last_name_popup" type="text"  class="form-control" required {% if last_name is defined %}
                        value="{{ last_name }}" {% endif %}>
                </div>
                <div class="form-group">
                    <label>Почта *</label>
                    <input name="email" id="email_popup" type="email" class="form-control" required {% if email is defined %}
                        value="{{ email }}" {% endif %}>
                </div>
                <div class="form-group">
                    <label>Компания</label>
                    <input name="company_name" id="company_name_popup" type="text" class="form-control" {% if company_name is defined %}
                        value="{{ company_name }}" {% endif %}>
                </div>
                <div class="form-group">
                    <label>Положение</label>
                    <input name="position" id="position_popup" type="text" class="form-control" {% if position is defined %}
                        value="{{ position }}" {% endif %}>
                </div>
                <div class="form-group">
                    <label>Телефон 1</label>
                    <input name="telephone_1" id="phone_1" type="tel" class="form-control" {% if phone_1 is defined %}
                        value="{{ phone_1 }}" {% endif %}>
                </div>
                <div class="form-group">
                    <label>Телефон 2</label>
                    <input name="telephone_2" id="phone_2" type="tel" class="form-control" {% if phone_2 is defined %}
                        value="{{ phone_2 }}" {% endif %}>
                </div>
                <div class="form-group">
                    <label>Телефон 3</label>
                    <input name="telephone_3" id="phone_3" type="tel" class="form-control"    {% if phone_3 is defined %}
                        value="{{ phone_3 }}" {% endif %}>
                </div>
                <div>
                    <a href="javascript:popUpHide()">
                        <button type="button" class="btn btn-secondary" style="margin-right: 5px" >Отмена</button>
                    </a>
                    <button id="send_new_data" type="submit" class="btn btn-primary float-right">Сохранить</button>
                </div>

            </form>

        </div>
    </div>
    {% if countOfWorkers == 0 %}
        <div class="p-3 mb-2 bg-warning text-dark">Нет ни одного пользователя</div>
    {% endif %}
    {% if error_message is defined%}
    {% endif %}

    <div class="mx-auto" style="width: 600px">
        <a href="{{ path('create_user') }}">Добавить нового пользователя</a>
    {% if workers is defined %}
        {% for worker in workers %}
            <div class="card">
                <div class="card-header">
                   {{ loop.index + 10 * (current - 1) }}
                </div>
                <div class="card-body">
                    <ul>
                        <li>{{ worker.firstName }}</li>
                        <li>{{ worker.lastName }}</li>
                        <li>{{ worker.email }}</li>
                        {% if worker.companyName is not empty %}<li>{{ worker.companyName }}</li>{% endif %}
                        {% if worker.position is not empty %}<li>{{ worker.position }}</li>{% endif %}
                        {% if worker.telephone1 is not empty %}<li>{{ worker.telephone1 }}</li>{% endif %}
                        {% if worker.telephone2 is not empty %}<li>{{ worker.telephone2 }}</li>{% endif %}
                        {% if worker.telephone3 is not empty %}<li>{{ worker.telephone3 }}</li>{% endif %}
                    </ul>
                </div>
                <div>
                    <a href="javascript:popUpShow({{ worker.id }})"><button class="btn btn-primary btn-sm float-right" style="margin-bottom: 20px;margin-right: 20px">
                        Редактировать</button>
                    </a>
                    <a href="{{ path('delete_by_id', {'id': worker.id}) }}">
                        <button class="btn btn-secondary btn-sm float-right" style="margin-right: 5px" >Удалить</button>
                    </a>
                </div>
            </div>
            <br>
        {% endfor %}
    {% endif %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% for index in indexes %}
                <li class="page-item  {% if index == current %} active {%  endif %} ">
                    <a class="page-link" href="{{ path('management', {'id': index}) }}">{{ index }}</a>
                </li>
            {% endfor %}
        </ul>
    </nav>

    </div>

{% endblock %}

templates/management/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Добавление нового человека{% endblock %}


{% block body %}
<div>
    <div>
        <a href="{{ path('management_redirect') }}">Просмотреть всех юзеров</a>
    </div>

    {% if error_list is defined %}
        <div class="p-3 mb-2 bg-danger text-white">
            Ошибочки вышли
            <ul>
                <li>{{ error_list }}</li>
            </ul>
        </div>
    {% elseif success_mess is defined %}
        <div class="p-3 mb-2 bg-success text-white">
            Операция прошла успешно
            <ul>
                <li>{{ success_mess }}</li>
            </ul>
        </div>

    {% endif %}
</div>

<div class="mx-auto" style="width: 600px">
    {#  В зависимости от сценария, сообщение пользователю будет разное  #}
    {% if header is defined %}
        <h1>header</h1>
    {% endif %}
    <form class="px-4 py-3" method="post" id="add_new_user" action="{{ path('add_user') }}">
        <div class="form-group">
            <label>Имя *</label>
            <input name="first_name" type="text" class="form-control" required {% if first_name is defined %}
                value="{{ first_name }}" {% endif %}>
        </div>
        <div class="form-group">
            <label>Фамилия *</label>
            <input name="last_name" type="text"  class="form-control" required {% if last_name is defined %}
                value="{{ last_name }}" {% endif %}>
        </div>
        <div class="form-group">
            <label>Почта *</label>
            <input name="email" type="email" class="form-control" required {% if email is defined %}
                value="{{ email }}" {% endif %}>
        </div>
        <div class="form-group">
            <label>Компания</label>
            <input name="company_name" type="text" class="form-control" {% if company_name is defined %}
                value="{{ company_name }}" {% endif %}>
        </div>
        <div class="form-group">
            <label>Положение</label>
            <input name="position" type="text" class="form-control" {% if position is defined %}
                value="{{ position }}" {% endif %}>
        </div>
        <div class="form-group">
            <label>Телефон 1</label>
            <input name="telephone_1" type="tel" class="form-control" {% if phone_1 is defined %}
                value="{{ phone_1 }}" {% endif %}>
        </div>
        <div class="form-group">
            <label>Телефон 2</label>
            <input name="telephone_2" type="tel" class="form-control" {% if phone_2 is defined %}
                value="{{ phone_2 }}" {% endif %}>
        </div>
        <div class="form-group">
            <label>Телефон 3</label>
            <input name="telephone_3" type="tel" class="form-control"    {% if phone_3 is defined %}
                value="{{ phone_3 }}" {% endif %}>
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>

{% endblock %}